apiVersion: batch/v1
kind: CronJob
metadata:
  name: telegram-scraper-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: telegram-scraper
            image: carlosmoreno7/telegram-scraper:latest
            imagePullPolicy: Always
            volumeMounts: 
            - name: telegram-session-storage # Nombre del volumen que se montará
              mountPath: /app/ # Donde se montará el volumen dentro del contenedor
          restartPolicy: OnFailure
          volumes: 
          - name: telegram-session-storage # Debe coincidir con el 'name' en volumeMounts
            persistentVolumeClaim:
              claimName: telegram-session-pvc # Nombre del PVC que hemos creado
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1