apiVersion: batch/v1
kind: CronJob
metadata:
  name: telegram-scraper-cronjob
  namespace: default # O el namespace que uses con ArgoCD
  labels:
    app: telegram-scraper
spec:
  schedule: "*/5 * 1 * *" # O tu horario deseado
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: telegram-scraper
            image: carlosmoreno7/telegram-scraper:latest # ¡Asegúrate de que este tag sea correcto!
            imagePullPolicy: Always # <--- ¡ESTO ES CLAVE!
            envFrom: # Para inyectar las credenciales desde el Secret
            - secretRef:
                name: telegram-scraper-secrets
            volumeMounts: # Monta el volumen persistente
            - name: telegram-session-storage
              mountPath: /app
          restartPolicy: OnFailure
          volumes: # Define el volumen que usará el PVC
          - name: telegram-session-storage
            persistentVolumeClaim:
              claimName: telegram-session-pvc
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1